#!/usr/bin/env bash

# pull in common functions
. ${BASEDIR}/hooks/dehydrated-bigip-common
# pull in config
. ${BASEDIR}/hooks/dehydrated-bigip-loadconfig

# dehydrated hooks

deploy_cert() {
  echo "entering deploy_cert()"
  for BIGIP_DEVICE in ${BIGIP_DEVICE_LIST} ; do
    echo "check if ${BIGIP_DEVICE} is Active in cluster";
    if isActive ; then
      echo "Active device, deploy cert $@  on ${BIGIP_DEVICE}"
      deploy_mgmt_cert $@ ${BIGIP_DEVICE}
    else
      echo "Device ${BIGIP_DEVICE} is passive in cluster, skip cert deployment"
    fi
  done
}

HANDLER="$1"; shift
if [ -n "$(type -t $HANDLER)" ] && [ "$(type -t $HANDLER)" = function ]; then
  "$HANDLER" "$@"
fi

# EOF
