#!/bin/bash

# pull in conf.d files
for i in ${BASEDIR}/conf.d/*.sh ; do
  . ${i}
done

# Provides an example for how to chain hooks together for deployment of
# certificates to BIGIP after successful DNS-01 validation
DEPLOY_HOOK="${BASEDIR}/hooks/dehydrated-bigip-deploy-management-certificate"

# lexicon first performs DNS-01 validation and obtains the certificate
# lexicon will NOT perform certificate deployment
# Refer to: https://github.com/AnalogJ/lexicon/blob/master/examples/dehydrated.default.sh
${BASEDIR}/hooks/dehydrated-lexicon "$@"

# the following will NOT perform challenge deployment/validation/cleanup etc
# use the deploy-traffic-certificate script to handle hook functions not
# not provided by this script

# The BIG-IP device should simply be the same as the hostname in this case
BIGIP_DEVICE=${2}

# Use the deploy hook
${DEPLOY_HOOK} $@ ${BIGIP_DEVICE}

# EOF
