#!/bin/bash

# pull in conf.d files
for i in ${BASEDIR}/conf.d/*.sh ; do
  . ${i}
done

REDEPLOY_USING_HOOK='hooks/dehydrated-bigip-deploy-traffic-certificate'

unchanged_cert() {
  ${BASEDIR}/${REDEPLOY_USING_HOOK} deploy_cert $@
}

HANDLER="$1"; shift
if [ -n "$(type -t $HANDLER)" ] && [ "$(type -t $HANDLER)" = function ]; then
  "$HANDLER" "$@"
fi

# EOF
