#!/usr/bin/env bash

# pull in conf.d files
for i in ${BASEDIR}/conf.d/*.sh ; do
  . ${i}
done

REDEPLOY_USING_HOOK='hooks/dehydrated-bigip-deploy-traffic-certificate'

unchanged_cert() {
  for BIGIP_DEVICE in ${BIGIP_DEVICE_LIST} ; do
    ${BASEDIR}/${REDEPLOY_USING_HOOK} deploy_cert $@ ${BIGIP_DEVICE}
  done
}

HANDLER="$1"; shift
if [ -n "$(type -t $HANDLER)" ] && [ "$(type -t $HANDLER)" = function ]; then
  "$HANDLER" "$@"
fi

# EOF
